import { PrismaClient } from "~/lib/generated/prisma";

const prisma = new PrismaClient();

export interface CreateSpouseInput {
	name: string;
	birthDate?: Date | string;
	marriageDate?: Date | string;
	divorceDate?: Date | string;
	status?: "married" | "divorced" | "widowed" | "partner";
	order?: number;
	memberId: string;
}

export interface UpdateSpouseInput {
	name?: string;
	birthDate?: Date | string | null;
	marriageDate?: Date | string | null;
	divorceDate?: Date | string | null;
	status?: "married" | "divorced" | "widowed" | "partner";
	order?: number;
}

/**
 * Spouse Service
 * Handles all database operations related to spouses/partners
 */
export class SpouseService {
	/**
	 * Create a new spouse record
	 * ID is auto-generated by database (UUID)
	 * Order is auto-calculated if not provided
	 */
	static async createSpouse(data: CreateSpouseInput) {
		// Auto-calculate order if not provided
		let order = data.order;
		if (!order) {
			const existingSpouses = await prisma.spouse.count({
				where: { memberId: data.memberId },
			});
			order = existingSpouses + 1;
		}

		return await prisma.spouse.create({
			data: {
				name: data.name,
				birthDate: data.birthDate ? new Date(data.birthDate) : null,
				marriageDate: data.marriageDate ? new Date(data.marriageDate) : null,
				divorceDate: data.divorceDate ? new Date(data.divorceDate) : null,
				status: data.status || "married",
				order: order,
				memberId: data.memberId,
			},
		});
	}

	/**
	 * Get all spouses for a family member
	 * Ordered by marriage order (1st, 2nd, 3rd spouse)
	 */
	static async getSpousesByMemberId(memberId: string) {
		return await prisma.spouse.findMany({
			where: { memberId },
			orderBy: [{ order: "asc" }, { marriageDate: "asc" }],
		});
	}

	/**
	 * Get a single spouse by ID
	 */
	static async getSpouseById(id: string) {
		return await prisma.spouse.findUnique({
			where: { id },
			include: {
				member: {
					select: {
						id: true,
						name: true,
					},
				},
			},
		});
	}

	/**
	 * Update spouse information
	 */
	static async updateSpouse(id: string, data: UpdateSpouseInput) {
		return await prisma.spouse.update({
			where: { id },
			data: {
				...(data.name && { name: data.name }),
				...(data.birthDate !== undefined && {
					birthDate: data.birthDate ? new Date(data.birthDate) : null,
				}),
				...(data.marriageDate !== undefined && {
					marriageDate: data.marriageDate ? new Date(data.marriageDate) : null,
				}),
				...(data.divorceDate !== undefined && {
					divorceDate: data.divorceDate ? new Date(data.divorceDate) : null,
				}),
				...(data.status && { status: data.status }),
				...(data.order !== undefined && { order: data.order }),
			},
		});
	}

	/**
	 * Delete a spouse record
	 */
	static async deleteSpouse(id: string) {
		return await prisma.spouse.delete({
			where: { id },
		});
	}

	/**
	 * Create multiple spouses for a member
	 * Automatically assigns order (1st, 2nd, 3rd, etc.)
	 */
	static async createMultipleSpouses(
		memberId: string,
		spouses: Omit<CreateSpouseInput, "memberId">[]
	) {
		// Get current spouse count
		const existingCount = await prisma.spouse.count({
			where: { memberId },
		});

		return await prisma.spouse.createMany({
			data: spouses.map((spouse, index) => ({
				name: spouse.name,
				birthDate: spouse.birthDate ? new Date(spouse.birthDate) : null,
				marriageDate: spouse.marriageDate
					? new Date(spouse.marriageDate)
					: null,
				divorceDate: spouse.divorceDate
					? new Date(spouse.divorceDate)
					: null,
				status: spouse.status || "married",
				order: spouse.order || existingCount + index + 1,
				memberId,
			})),
		});
	}

	/**
	 * Get family member with all their spouses
	 */
	static async getMemberWithSpouses(memberId: string) {
		return await prisma.familyMember.findUnique({
			where: { id: memberId },
			include: {
				spouses: {
					orderBy: { marriageDate: "asc" },
				},
			},
		});
	}

	/**
	 * Search spouses by name
	 */
	static async searchSpousesByName(searchTerm: string) {
		return await prisma.spouse.findMany({
			where: {
				name: {
					contains: searchTerm,
					mode: "insensitive",
				},
			},
			include: {
				member: {
					select: {
						id: true,
						name: true,
					},
				},
			},
		});
	}

	/**
	 * Get all spouses in a family tree
	 */
	static async getSpousesByTreeId(treeId: string) {
		return await prisma.spouse.findMany({
			where: {
				member: {
					treeId,
				},
			},
			include: {
				member: {
					select: {
						id: true,
						name: true,
					},
				},
			},
		});
	}

	/**
	 * Get only current/active spouses (married or partner status)
	 */
	static async getCurrentSpousesByMemberId(memberId: string) {
		return await prisma.spouse.findMany({
			where: {
				memberId,
				status: {
					in: ["married", "partner"],
				},
			},
			orderBy: [{ order: "asc" }],
		});
	}

	/**
	 * Get former spouses (divorced or widowed)
	 */
	static async getFormerSpousesByMemberId(memberId: string) {
		return await prisma.spouse.findMany({
			where: {
				memberId,
				status: {
					in: ["divorced", "widowed"],
				},
			},
			orderBy: [{ order: "asc" }],
		});
	}

	/**
	 * Mark spouse as divorced
	 */
	static async markAsDivorced(id: string, divorceDate?: Date | string) {
		return await prisma.spouse.update({
			where: { id },
			data: {
				status: "divorced",
				divorceDate: divorceDate ? new Date(divorceDate) : new Date(),
			},
		});
	}

	/**
	 * Mark spouse as widowed
	 */
	static async markAsWidowed(id: string) {
		return await prisma.spouse.update({
			where: { id },
			data: {
				status: "widowed",
			},
		});
	}
}

export default SpouseService;
