import { IFamily } from "~/interfaces/family.interface";

/**
 * Real-world spouse scenarios demonstrating different relationship types
 */

// Scenario 1: Person with single spouse (still married)
export const singleSpouseExample: IFamily = {
	id: "1",
	name: "John Chikwape",
	birthDate: "1950-01-15",
	parentId: null,
	treeId: "tree1",
	spouses: [
		{
			id: "spouse1", // Auto-generated by DB if not provided
			name: "Mary Smith",
			birthDate: "1952-03-20",
			marriageDate: "1975-06-10",
			status: "married",
			order: 1, // First spouse
		},
	],
	children: [],
};

// Scenario 2: Person who remarried (divorced from first, married to second)
export const remarriedExample: IFamily = {
	id: "2",
	name: "David Chikwape",
	birthDate: "1976-08-12",
	parentId: "1",
	treeId: "tree1",
	spouses: [
		{
			id: "spouse2",
			name: "Sarah Johnson",
			birthDate: "1978-05-15",
			marriageDate: "2000-04-20",
			divorceDate: "2012-11-15",
			status: "divorced",
			order: 1, // First spouse
		},
		{
			id: "spouse3",
			name: "Lisa Brown",
			birthDate: "1980-11-30",
			marriageDate: "2015-09-12",
			status: "married",
			order: 2, // Second spouse
		},
	],
	children: [],
};

// Scenario 3: Widowed person who remarried
export const widowedRemarriedExample: IFamily = {
	id: "3",
	name: "Grace Chikwape",
	birthDate: "1980-04-25",
	parentId: "1",
	treeId: "tree1",
	spouses: [
		{
			id: "spouse4",
			name: "Peter Wilson",
			birthDate: "1979-09-10",
			marriageDate: "2005-07-15",
			status: "widowed", // Peter passed away
			order: 1,
		},
		{
			id: "spouse5",
			name: "Thomas Anderson",
			birthDate: "1981-03-22",
			marriageDate: "2020-06-20",
			status: "married",
			order: 2,
		},
	],
	children: [],
};

// Scenario 4: Person with partner (not formally married)
export const partnerExample: IFamily = {
	id: "4",
	name: "Emma Chikwape",
	birthDate: "2001-02-14",
	parentId: "2",
	treeId: "tree1",
	spouses: [
		{
			name: "Michael Davis",
			birthDate: "2000-07-22",
			status: "partner", // Living together but not married
			order: 1,
		},
	],
	children: [],
};

// Scenario 5: Multiple marriages (3 times)
export const multipleMarriagesExample: IFamily = {
	id: "5",
	name: "Robert Chikwape",
	birthDate: "1955-06-30",
	parentId: null,
	treeId: "tree1",
	spouses: [
		{
			name: "First Wife",
			marriageDate: "1980-05-10",
			divorceDate: "1990-03-15",
			status: "divorced",
			order: 1,
		},
		{
			name: "Second Wife",
			marriageDate: "1992-08-20",
			divorceDate: "2005-12-10",
			status: "divorced",
			order: 2,
		},
		{
			name: "Third Wife",
			marriageDate: "2008-04-15",
			status: "married",
			order: 3,
		},
	],
	children: [],
};

// Scenario 6: Person with no spouse yet
export const noSpouseExample: IFamily = {
	id: "6",
	name: "James Chikwape",
	birthDate: "2016-12-05",
	parentId: "2",
	treeId: "tree1",
	spouses: [], // No spouses
	children: [],
};

/**
 * How to add spouses with different scenarios using the API/Service
 */

// Example 1: Add first spouse
/*
await SpouseService.createSpouse({
  name: "Mary Smith",
  birthDate: "1952-03-20",
  marriageDate: "1975-06-10",
  status: "married",
  memberId: "member-id"
  // order will be auto-calculated as 1
  // id will be auto-generated
});
*/

// Example 2: Add second spouse (remarriage)
/*
await SpouseService.createSpouse({
  name: "Lisa Brown",
  birthDate: "1980-11-30",
  marriageDate: "2015-09-12",
  status: "married",
  memberId: "member-id"
  // order will be auto-calculated as 2
});
*/

// Example 3: Mark spouse as divorced
/*
await SpouseService.markAsDivorced("spouse-id", "2012-11-15");
*/

// Example 4: Mark spouse as widowed
/*
await SpouseService.markAsWidowed("spouse-id");
*/

// Example 5: Add partner (not married)
/*
await SpouseService.createSpouse({
  name: "Michael Davis",
  birthDate: "2000-07-22",
  status: "partner",
  memberId: "member-id"
  // No marriageDate for partners
});
*/

// Example 6: Get only current spouses
/*
const currentSpouses = await SpouseService.getCurrentSpousesByMemberId("member-id");
// Returns only married or partner status
*/

// Example 7: Get former spouses
/*
const formerSpouses = await SpouseService.getFormerSpousesByMemberId("member-id");
// Returns only divorced or widowed status
*/

// Example 8: Add multiple spouses at once
/*
await SpouseService.createMultipleSpouses("member-id", [
  {
    name: "First Spouse",
    marriageDate: "2000-01-01",
    divorceDate: "2010-01-01",
    status: "divorced"
  },
  {
    name: "Second Spouse",
    marriageDate: "2012-01-01",
    status: "married"
  }
]);
// Orders will be auto-calculated as 1, 2, etc.
*/

/**
 * UI Display Examples
 * 
 * Married spouse:
 * ┌─────────────────────┐
 * │ 👤 Mary Smith       │
 * │ 💍 Married: 1975... │
 * └─────────────────────┘
 * 
 * Divorced spouse (2nd marriage):
 * ┌─────────────────────┐
 * │ 👤 Sarah Johnson 💔 │
 * │ [2nd]               │
 * │ 💍 Married: 2000... │
 * │ 💔 Divorced: 2012...│
 * └─────────────────────┘
 * 
 * Widowed spouse:
 * ┌─────────────────────┐
 * │ 👤 Peter Wilson 🕊️  │
 * │ 💍 Married: 2005... │
 * └─────────────────────┘
 * 
 * Partner (not married):
 * ┌─────────────────────┐
 * │ 👤 Michael Davis 💕 │
 * │ 🎂 Born: 2000...    │
 * └─────────────────────┘
 */
